# -*- coding: utf-8 -*-
"""classification_using_SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X8WlV0oLcL38ZTmziN6p7FKCLyLxWTNp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TATAMOTORS 2.csv')
df.head()

df.describe()

df.info()

A = df[['Profit_achieveable','Loss_achieveable']]
B = df['class_profit']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(A, B, test_size = 0.20)
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)
print(model.score(X_train, y_train)*100)
print(model.score(X_test, y_test)*100)

from mlxtend.plotting import plot_decision_regions
f = np.array(X_test)
t = np.array(y_test).ravel()
plt.xlabel("Parametres")
plt.ylabel("class_profit")
plt.title("Multiclass classification")
plot_decision_regions(f,t,clf = model)
plt.show()